// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DocinadeApp.Data;

#nullable disable

namespace DocinadeApp.Migrations
{
    [DbContext(typeof(RubricasDbContext))]
    [Migration("20251024040453_ActualizarEsquema_Profesores_2025")]
    partial class ActualizarEsquema_Profesores_2025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DocinadeApp.Models.Academic.MateriaPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Abierta");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodoAcademicoId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoAcademicoId");

                    b.HasIndex("PeriodoAcademicoId1");

                    b.ToTable("MateriaPeriodos");
                });

            modelBuilder.Entity("DocinadeApp.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<bool>("EsModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HoraLlegada")
                        .HasColumnType("time");

                    b.Property<string>("Justificacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RegistradoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Asistencias_Estado");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Asistencias_Fecha");

                    b.HasIndex("FechaRegistro")
                        .HasDatabaseName("IX_Asistencias_FechaRegistro");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("IX_Asistencias_GrupoId");

                    b.HasIndex("MateriaId")
                        .HasDatabaseName("IX_Asistencias_MateriaId");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("EstudianteId", "GrupoId", "MateriaId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("IX_Asistencias_Unique_Estudiante_Grupo_Materia_Fecha");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("DocinadeApp.Models.Audit.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClientInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Information");

                    b.Property<string>("Metadata")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("NewValues")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("OldValues")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Referrer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DocinadeApp.Models.AuditoriaOperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("ntext");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("ntext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("FechaOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("OperacionExitosa")
                        .HasColumnType("bit");

                    b.Property<int>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FechaOperacion")
                        .HasDatabaseName("IX_AuditoriaOperacion_FechaOperacion");

                    b.HasIndex("RegistroId")
                        .HasDatabaseName("IX_AuditoriaOperacion_RegistroId");

                    b.HasIndex("TablaAfectada")
                        .HasDatabaseName("IX_AuditoriaOperacion_TablaAfectada");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_AuditoriaOperacion_UsuarioId");

                    b.HasIndex("TablaAfectada", "RegistroId")
                        .HasDatabaseName("IX_AuditoriaOperacion_Tabla_Registro");

                    b.ToTable("AuditoriasOperaciones");
                });

            modelBuilder.Entity("DocinadeApp.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("ConfiguracionesSistema");
                });

            modelBuilder.Entity("DocinadeApp.Models.CuadernoCalificador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoAcademicoId");

                    b.ToTable("CuadernosCalificadores");
                });

            modelBuilder.Entity("DocinadeApp.Models.CuadernoInstrumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuadernoCalificadorId")
                        .HasColumnType("int");

                    b.Property<bool>("EsObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("PonderacionPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RubricaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuadernoCalificadorId");

                    b.HasIndex("RubricaId");

                    b.ToTable("CuadernoInstrumentos");
                });

            modelBuilder.Entity("DocinadeApp.Models.DetalleEvaluacion", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("IdEvaluacion")
                        .HasColumnType("int");

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<decimal>("PuntosObtenidos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdEvaluacion");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdNivel");

                    b.ToTable("DetallesEvaluacion");
                });

            modelBuilder.Entity("DocinadeApp.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("DireccionCorreo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Grupos")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("int");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("DireccionCorreo");

                    b.HasIndex("NumeroId")
                        .IsUnique();

                    b.HasIndex("PeriodoAcademicoId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("DocinadeApp.Models.EstudianteEmpadronamiento", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<string>("AdaptacionesPrevias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Alergias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Barrio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Canton")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CentroMedicoHabitual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CondicionesMedicas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactoEmergencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoAlterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Distrito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentosPendientesJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("DocumentosRecibidosJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EtapaActual")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaEntregaDocumentos")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEtapa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoPoliza")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InstitucionProcedencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Medicamentos")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreMadre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombrePadre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreTutor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NotasInternas")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("NumeroId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PromedioAnterior")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RelacionEmergencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeguroMedico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TelefonoAlterno")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoEmergencia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UltimoNivelCursado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEtapa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("EtapaActual")
                        .HasDatabaseName("IX_EstudianteEmpadronamiento_EtapaActual");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_EstudianteEmpadronamiento_FechaCreacion");

                    b.HasIndex("NumeroId")
                        .HasDatabaseName("IX_EstudianteEmpadronamiento_NumeroId");

                    b.ToTable("EstudiantesEmpadronamiento");
                });

            modelBuilder.Entity("DocinadeApp.Models.EstudianteGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AsignadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EsGrupoPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaDesasignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoAsignacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoPorId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_EstudianteGrupos_Estado");

                    b.HasIndex("FechaAsignacion")
                        .HasDatabaseName("IX_EstudianteGrupos_FechaAsignacion");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("IX_EstudianteGrupos_GrupoId");

                    b.HasIndex("EstudianteId", "GrupoId", "Estado")
                        .HasDatabaseName("IX_EstudianteGrupos_Unique_Activo")
                        .HasFilter("[Estado] = 'Activo'");

                    b.ToTable("EstudianteGrupos");
                });

            modelBuilder.Entity("DocinadeApp.Models.Evaluacion", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BORRADOR");

                    b.Property<string>("EvaluadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdRubrica")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TiempoEvaluacionMinutos")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPuntos")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdEvaluacion");

                    b.HasIndex("EvaluadoPorId");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdRubrica");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("DocinadeApp.Models.GrupoCalificacion", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGrupo");

                    b.ToTable("GruposCalificacion");
                });

            modelBuilder.Entity("DocinadeApp.Models.GrupoEstudiante", b =>
                {
                    b.Property<int>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoId"));

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoGrupo")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoGrupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrupoId");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_GruposEstudiantes_Estado");

                    b.HasIndex("IdTipoGrupo")
                        .HasDatabaseName("IX_GruposEstudiantes_IdTipoGrupo");

                    b.HasIndex("PeriodoAcademicoId");

                    b.HasIndex("Codigo", "PeriodoAcademicoId")
                        .IsUnique()
                        .HasDatabaseName("IX_GruposEstudiantes_Codigo_Periodo");

                    b.ToTable("GruposEstudiantes");
                });

            modelBuilder.Entity("DocinadeApp.Models.GrupoMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("GrupoId", "MateriaId")
                        .IsUnique()
                        .HasDatabaseName("IX_GrupoMaterias_Unique");

                    b.ToTable("GrupoMaterias");
                });

            modelBuilder.Entity("DocinadeApp.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Departamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Institucion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroIdentificacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastLoginDate");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique()
                        .HasFilter("[NumeroIdentificacion] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DocinadeApp.Models.InstrumentoEvaluacion", b =>
                {
                    b.Property<int>("InstrumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentoId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstrumentoId");

                    b.ToTable("InstrumentosEvaluacion");
                });

            modelBuilder.Entity("DocinadeApp.Models.InstrumentoMateria", b =>
                {
                    b.Property<int>("InstrumentoEvaluacionId")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrdenPresentacion")
                        .HasColumnType("int");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("int");

                    b.HasKey("InstrumentoEvaluacionId", "MateriaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoAcademicoId");

                    b.ToTable("InstrumentoMaterias");
                });

            modelBuilder.Entity("DocinadeApp.Models.InstrumentoRubrica", b =>
                {
                    b.Property<int>("InstrumentoEvaluacionId")
                        .HasColumnType("int");

                    b.Property<int>("RubricaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("InstrumentoId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdenPresentacion")
                        .HasColumnType("int");

                    b.Property<decimal>("Ponderacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("InstrumentoEvaluacionId", "RubricaId");

                    b.HasIndex("RubricaId");

                    b.ToTable("InstrumentoRubricas");
                });

            modelBuilder.Entity("DocinadeApp.Models.ItemEvaluacion", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRubrica")
                        .HasColumnType("int");

                    b.Property<string>("NombreItem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OrdenItem")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("IdItem");

                    b.HasIndex("IdRubrica");

                    b.ToTable("ItemsEvaluacion");
                });

            modelBuilder.Entity("DocinadeApp.Models.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CicloSugerido")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MateriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("DocinadeApp.Models.MateriaRequisito", b =>
                {
                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("RequisitoId")
                        .HasColumnType("int");

                    b.HasKey("MateriaId", "RequisitoId");

                    b.HasIndex("RequisitoId");

                    b.ToTable("MateriaRequisitos");
                });

            modelBuilder.Entity("DocinadeApp.Models.NivelCalificacion", b =>
                {
                    b.Property<int>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivel"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<string>("NombreNivel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrdenNivel")
                        .HasColumnType("int");

                    b.HasKey("IdNivel");

                    b.HasIndex("IdGrupo");

                    b.ToTable("NivelesCalificacion");
                });

            modelBuilder.Entity("DocinadeApp.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroPeriodo")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaFin");

                    b.HasIndex("FechaInicio");

                    b.ToTable("PeriodosAcademicos");
                });

            modelBuilder.Entity("DocinadeApp.Models.Rubrica", b =>
                {
                    b.Property<int>("IdRubrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRubrica"));

                    b.Property<string>("CreadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EsPublica")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreRubrica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("IdRubrica");

                    b.HasIndex("CreadoPorId");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("ModificadoPorId");

                    b.ToTable("Rubricas");
                });

            modelBuilder.Entity("DocinadeApp.Models.RubricaNivel", b =>
                {
                    b.Property<int>("IdRubrica")
                        .HasColumnType("int");

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<int>("OrdenEnRubrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdRubrica", "IdNivel");

                    b.HasIndex("IdNivel");

                    b.ToTable("RubricaNiveles");
                });

            modelBuilder.Entity("DocinadeApp.Models.TipoGrupoCatalogo", b =>
                {
                    b.Property<int>("IdTipoGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoGrupo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoGrupo");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_TiposGrupo_Estado");

                    b.HasIndex("FechaRegistro")
                        .HasDatabaseName("IX_TiposGrupo_FechaRegistro");

                    b.ToTable("TiposGrupo");
                });

            modelBuilder.Entity("DocinadeApp.Models.ValorRubrica", b =>
                {
                    b.Property<int>("IdValor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValor"));

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<int>("IdRubrica")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPuntos")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("IdValor");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdNivel");

                    b.HasIndex("IdRubrica", "IdItem", "IdNivel")
                        .IsUnique()
                        .HasDatabaseName("IX_ValorRubrica_Unique");

                    b.ToTable("ValoresRubrica");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocinadeApp.Models.Academic.MateriaPeriodo", b =>
                {
                    b.HasOne("DocinadeApp.Models.Materia", "Materia")
                        .WithMany("Ofertas")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany()
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.PeriodoAcademico", null)
                        .WithMany("Ofertas")
                        .HasForeignKey("PeriodoAcademicoId1");

                    b.Navigation("Materia");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("DocinadeApp.Models.Asistencia", b =>
                {
                    b.HasOne("DocinadeApp.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.GrupoEstudiante", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Estudiante");

                    b.Navigation("Grupo");

                    b.Navigation("Materia");

                    b.Navigation("ModificadoPor");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("DocinadeApp.Models.AuditoriaOperacion", b =>
                {
                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DocinadeApp.Models.CuadernoCalificador", b =>
                {
                    b.HasOne("DocinadeApp.Models.Materia", "Materia")
                        .WithMany("CuadernosCalificadores")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany()
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("DocinadeApp.Models.CuadernoInstrumento", b =>
                {
                    b.HasOne("DocinadeApp.Models.CuadernoCalificador", "CuadernoCalificador")
                        .WithMany("CuadernoInstrumentos")
                        .HasForeignKey("CuadernoCalificadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Rubrica", "Rubrica")
                        .WithMany()
                        .HasForeignKey("RubricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuadernoCalificador");

                    b.Navigation("Rubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.DetalleEvaluacion", b =>
                {
                    b.HasOne("DocinadeApp.Models.Evaluacion", "Evaluacion")
                        .WithMany("DetallesEvaluacion")
                        .HasForeignKey("IdEvaluacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.ItemEvaluacion", "ItemEvaluacion")
                        .WithMany("DetallesEvaluacion")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.NivelCalificacion", "NivelCalificacion")
                        .WithMany("DetallesEvaluacion")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluacion");

                    b.Navigation("ItemEvaluacion");

                    b.Navigation("NivelCalificacion");
                });

            modelBuilder.Entity("DocinadeApp.Models.Estudiante", b =>
                {
                    b.HasOne("DocinadeApp.Models.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany("Estudiantes")
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("DocinadeApp.Models.EstudianteEmpadronamiento", b =>
                {
                    b.HasOne("DocinadeApp.Models.Estudiante", "Estudiante")
                        .WithOne()
                        .HasForeignKey("DocinadeApp.Models.EstudianteEmpadronamiento", "IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("DocinadeApp.Models.EstudianteGrupo", b =>
                {
                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", "AsignadoPor")
                        .WithMany()
                        .HasForeignKey("AsignadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DocinadeApp.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.GrupoEstudiante", "Grupo")
                        .WithMany("EstudianteGrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignadoPor");

                    b.Navigation("Estudiante");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("DocinadeApp.Models.Evaluacion", b =>
                {
                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", "EvaluadoPor")
                        .WithMany("EvaluacionesRealizadas")
                        .HasForeignKey("EvaluadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DocinadeApp.Models.Estudiante", "Estudiante")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Rubrica", "Rubrica")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdRubrica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("EvaluadoPor");

                    b.Navigation("Rubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.GrupoEstudiante", b =>
                {
                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DocinadeApp.Models.TipoGrupoCatalogo", "TipoGrupoCatalogo")
                        .WithMany("GruposEstudiantes")
                        .HasForeignKey("IdTipoGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany()
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("PeriodoAcademico");

                    b.Navigation("TipoGrupoCatalogo");
                });

            modelBuilder.Entity("DocinadeApp.Models.GrupoMateria", b =>
                {
                    b.HasOne("DocinadeApp.Models.GrupoEstudiante", "Grupo")
                        .WithMany("GrupoMaterias")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("DocinadeApp.Models.InstrumentoMateria", b =>
                {
                    b.HasOne("DocinadeApp.Models.InstrumentoEvaluacion", "InstrumentoEvaluacion")
                        .WithMany("InstrumentoMaterias")
                        .HasForeignKey("InstrumentoEvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Materia", "Materia")
                        .WithMany("InstrumentoMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany()
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstrumentoEvaluacion");

                    b.Navigation("Materia");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("DocinadeApp.Models.InstrumentoRubrica", b =>
                {
                    b.HasOne("DocinadeApp.Models.InstrumentoEvaluacion", "InstrumentoEvaluacion")
                        .WithMany("InstrumentoRubricas")
                        .HasForeignKey("InstrumentoEvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Rubrica", "Rubrica")
                        .WithMany()
                        .HasForeignKey("RubricaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstrumentoEvaluacion");

                    b.Navigation("Rubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.ItemEvaluacion", b =>
                {
                    b.HasOne("DocinadeApp.Models.Rubrica", "Rubrica")
                        .WithMany("ItemsEvaluacion")
                        .HasForeignKey("IdRubrica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.MateriaRequisito", b =>
                {
                    b.HasOne("DocinadeApp.Models.Materia", "Materia")
                        .WithMany("EsRequisitoPara")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Materia", "Requisito")
                        .WithMany("Prerequisitos")
                        .HasForeignKey("RequisitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Requisito");
                });

            modelBuilder.Entity("DocinadeApp.Models.NivelCalificacion", b =>
                {
                    b.HasOne("DocinadeApp.Models.GrupoCalificacion", "GrupoCalificacion")
                        .WithMany("NivelesCalificacion")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_NivelesCalificacion_GruposCalificacion_IdGrupo");

                    b.Navigation("GrupoCalificacion");
                });

            modelBuilder.Entity("DocinadeApp.Models.Rubrica", b =>
                {
                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", "CreadoPor")
                        .WithMany("RubricasCreadas")
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DocinadeApp.Models.GrupoCalificacion", "GrupoCalificacion")
                        .WithMany("Rubricas")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Rubricas_GruposCalificacion_IdGrupo");

                    b.HasOne("DocinadeApp.Models.Identity.ApplicationUser", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreadoPor");

                    b.Navigation("GrupoCalificacion");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("DocinadeApp.Models.RubricaNivel", b =>
                {
                    b.HasOne("DocinadeApp.Models.NivelCalificacion", "NivelCalificacion")
                        .WithMany("RubricaNiveles")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Rubrica", "Rubrica")
                        .WithMany("RubricaNiveles")
                        .HasForeignKey("IdRubrica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelCalificacion");

                    b.Navigation("Rubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.ValorRubrica", b =>
                {
                    b.HasOne("DocinadeApp.Models.ItemEvaluacion", "ItemEvaluacion")
                        .WithMany("ValoresRubrica")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.NivelCalificacion", "NivelCalificacion")
                        .WithMany("ValoresRubrica")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocinadeApp.Models.Rubrica", "Rubrica")
                        .WithMany("ValoresRubrica")
                        .HasForeignKey("IdRubrica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemEvaluacion");

                    b.Navigation("NivelCalificacion");

                    b.Navigation("Rubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.CuadernoCalificador", b =>
                {
                    b.Navigation("CuadernoInstrumentos");
                });

            modelBuilder.Entity("DocinadeApp.Models.Estudiante", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("DocinadeApp.Models.Evaluacion", b =>
                {
                    b.Navigation("DetallesEvaluacion");
                });

            modelBuilder.Entity("DocinadeApp.Models.GrupoCalificacion", b =>
                {
                    b.Navigation("NivelesCalificacion");

                    b.Navigation("Rubricas");
                });

            modelBuilder.Entity("DocinadeApp.Models.GrupoEstudiante", b =>
                {
                    b.Navigation("EstudianteGrupos");

                    b.Navigation("GrupoMaterias");
                });

            modelBuilder.Entity("DocinadeApp.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("EvaluacionesRealizadas");

                    b.Navigation("RubricasCreadas");
                });

            modelBuilder.Entity("DocinadeApp.Models.InstrumentoEvaluacion", b =>
                {
                    b.Navigation("InstrumentoMaterias");

                    b.Navigation("InstrumentoRubricas");
                });

            modelBuilder.Entity("DocinadeApp.Models.ItemEvaluacion", b =>
                {
                    b.Navigation("DetallesEvaluacion");

                    b.Navigation("ValoresRubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.Materia", b =>
                {
                    b.Navigation("CuadernosCalificadores");

                    b.Navigation("EsRequisitoPara");

                    b.Navigation("InstrumentoMaterias");

                    b.Navigation("Ofertas");

                    b.Navigation("Prerequisitos");
                });

            modelBuilder.Entity("DocinadeApp.Models.NivelCalificacion", b =>
                {
                    b.Navigation("DetallesEvaluacion");

                    b.Navigation("RubricaNiveles");

                    b.Navigation("ValoresRubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.PeriodoAcademico", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("DocinadeApp.Models.Rubrica", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("ItemsEvaluacion");

                    b.Navigation("RubricaNiveles");

                    b.Navigation("ValoresRubrica");
                });

            modelBuilder.Entity("DocinadeApp.Models.TipoGrupoCatalogo", b =>
                {
                    b.Navigation("GruposEstudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
