SELECT TOP (1000) [Id]
      ,[ProfesorId]
      ,[GrupoId]
      ,[FechaAsignacion]
      ,[FechaInicio]
      ,[FechaFin]
      ,[Estado]
      ,[Observaciones]
  FROM [RubricasDb].[dbo].[ProfesorGuia]