SELECT TOP (1000) [Id]
      ,[ProfesorId]
      ,[TipoCapacitacion]
      ,[NombreCapacitacion]
      ,[InstitucionOrganizadora]
      ,[AreaConocimiento]
      ,[Modalidad]
      ,[FechaInicio]
      ,[FechaFin]
      ,[HorasCapacitacion]
      ,[CalificacionObtenida]
      ,[CertificadoObtenido]
      ,[FechaCreacion]
  FROM [RubricasDb].[dbo].[ProfesorCapacitacion]