SELECT TOP (1000) [Id]
      ,[ProfesorId]
      ,[GrupoId]
      ,[MateriaId]
      ,[PeriodoAcademicoId]
      ,[EsProfesorPrincipal]
      ,[FechaAsignacion]
      ,[FechaInicio]
      ,[FechaFin]
      ,[Estado]
      ,[AulaAsignada]
      ,[Observaciones]
  FROM [RubricasDb].[dbo].[ProfesorGrupo]