SELECT TOP (1000) [Id]
      ,[ProfesorId]
      ,[TipoFormacion]
      ,[InstitucionEducativa]
      ,[PaisInstitucion]
      ,[TituloObtenido]
      ,[AnioInicio]
      ,[AnioFinalizacion]
      ,[EnCurso]
      ,[PromedioGeneral]
      ,[EsTituloReconocidoCONARE]
      ,[NumeroReconocimiento]
      ,[FechaCreacion]
  FROM [RubricasDb].[dbo].[ProfesorFormacionAcademica]