SELECT TOP (1000) [Id]
      ,[Nombre]
      ,[Apellidos]
      ,[IsActive]
      ,[CreatedDate]
      ,[LastLoginDate]
      ,[NumeroIdentificacion]
      ,[Institucion]
      ,[Departamento]
      ,[FechaRegistro]
      ,[UltimoAcceso]
      ,[Activo]
      ,[Observaciones]
      ,[UserName]
      ,[NormalizedUserName]
      ,[Email]
      ,[NormalizedEmail]
      ,[EmailConfirmed]
      ,[PasswordHash]
      ,[SecurityStamp]
      ,[ConcurrencyStamp]
      ,[PhoneNumber]
      ,[PhoneNumberConfirmed]
      ,[TwoFactorEnabled]
      ,[LockoutEnd]
      ,[LockoutEnabled]
      ,[AccessFailedCount]
  FROM [RubricasDb].[dbo].[AspNetUsers]